version: 0.0
os: linux 
files:
  - source: /
    destination: /var/www/
hooks:
  BeforeInstall:
    - location: scripts/before_install
      timeout: 300
      runas: root
  Install:
    - location: scripts/after_install
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server  
      timeout: 300
      runas: root
